# ? properties ??? yml? ??, ? ??? application ??? ??? ?? ???? ? ?. (??? ??)
server:
  port: 7777

# spring - mysql driver config
spring:
  datasource: # spring? ??? ??? ???? ?????? ????
    driver-class-name: com.mysql.cj.jdbc.Driver # sql ???? ??
    url: jdbc:mysql://localhost:3306/menudb
    username: ohgiraffers
    password: ohgiraffers

# Mybatis mapper.xml file? IoC Container? ??? ? ?? ?? ?? ??
# menuMapper.xml ? bean?? ???? ??
mybatis:
  # mappers/*.xml : mappers ???? ??? ???? .xml? ??? ?? ??
  # mappers/**.xml : mappers ???? ?? ?? ?? ?????? .xml? ??? ?? ??
  mapper-locations: mappers/**/*.xml